### ISSUE TITLE
problems with modifiers

### ISSUE THREAD

**Issue by questor** [breckinloggins/ngtemplate#1]
are you still maintaining this library? I've found a problem with the modifiers. for example in the html_escape you go through every character and test if it has to be replaced. if the character does not need a replacement you write it to the output string via sb_append_ch which checks and sets the terminating zero-byte (and checks for pos == size-1). but when the character needs to be replaced by sb_append_strn you don't put the zero-byte at the end and hence you check only for sdiff > 0.
when you convert a replacement character in your output string it can happen that after sb_append_strn your sb->size == sb->pos, but in sb_append_ch you check for sb->size == sb->size-1, so you do NOT reallocate your string buffer and everything crashes...

I think by convention your stringbuild-strings are not zero terminated, hence you need to fix the macro sb_append_ch, am I right? (this also would make it a bit faster, too)

[edit]: my proposed fixed macro:
# define sb_append_ch(sb, ch)    {                                                       \

```
    if ((sb)->pos == (sb)->size )   {                                               \
        (sb)->reallocs++;                                                           \
        (sb)->size = (sb)->size + ((sb)->size >> 2)+ 1;                             \
        (sb)->cstr = (char*)realloc((sb)->cstr, (sb)->size );                       \
    }                                                                               \
    (sb)->cstr[(sb)->pos++] = ch;                                                   \
}
```

**Comment by breckinloggins** [comment]
Yup, still maintaining it. Thanks for the bug report and the suggested fix. I'll try it out today. Feel free to send me a pull request if you'd like to make your contribution "official" for github stats.

**Comment by questor** [comment]
made a pull request on libuseful... thanks for releasing the lib, it's really helpful!

**Comment by breckinloggins** [comment]
Glad you like it!  The pull request was merged and I made some further fixes for building on Linux systems.
